version: '3.5'

services:
  storage-bootcamp:
    container_name: storage-bootcamp
    image: liyaodev/storage-bootcamp-env:v1.0.0
    # 本地构建
    build:
      context: .
      dockerfile: build/docker/build_env/Dockerfile
    ports:
      - 8888:8888
    environment:
      - ETCD_ENDPOINTS=${ETCD_ENDPOINTS}
    volumes:
      - .:/go/src/github.com/codetodo-io/storage-bootcamp:delegated
      - ${STORAGE_BOOTCAMP_ROOT_DIR:-.}/volumes/vscode-extensions:/www/.vscode-server
    working_dir: /go/src/github.com/codetodo-io/storage-bootcamp

  etcd:
    container_name: storage-etcd
    image: bitnami/etcd:3.5.2
    ports:
      - 2379:2379
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1002
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ${DOCKER_ROOT_DIR:-.}/volumes/etcd/data:/bitnami/etcd

networks:
  default:
    name: storage_bootcamp_dev
